<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" ignored="0" total="4" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="17993" started-at="2018-08-02T10:25:32Z" finished-at="2018-08-02T10:25:50Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="17993" started-at="2018-08-02T10:25:32Z" finished-at="2018-08-02T10:25:50Z">
      <class name="com.c2info.EG360_DashboardTCs.TodayValues">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.c2info.EG360_DashboardTCs.TodayValues@42f93a98]" name="setup" is-config="true" duration-ms="10525" started-at="2018-08-02T15:55:32Z" finished-at="2018-08-02T15:55:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.c2info.EG360_DashboardTCs.TodayValues@42f93a98]" name="beforeMethod" is-config="true" duration-ms="2" started-at="2018-08-02T15:55:43Z" finished-at="2018-08-02T15:55:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.c2info.EG360_DashboardTCs.TodayValues.verifyTodaySalesValue() throws java.sql.SQLException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="verifyTodaySalesValue()[pri:0, instance:com.c2info.EG360_DashboardTCs.TodayValues@42f93a98]" name="verifyTodaySalesValue" duration-ms="5013" started-at="2018-08-02T15:55:43Z" finished-at="2018-08-02T15:55:48Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [75.08] but found [21.5]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [75.08] but found [21.5]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at com.c2info.EG360_DashboardTCs.TodayValues.verifyTodaySalesValue(TodayValues.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTodaySalesValue -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.c2info.EG360_DashboardTCs.TodayValues@42f93a98]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-08-02T15:55:48Z" finished-at="2018-08-02T15:55:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyTodaySalesValue status=FAILURE method=TodayValues.verifyTodaySalesValue()[pri:0, instance:com.c2info.EG360_DashboardTCs.TodayValues@42f93a98] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="verifyTodayPurchaseValue()[pri:1, instance:com.c2info.EG360_DashboardTCs.TodayValues@42f93a98]" name="verifyTodayPurchaseValue" duration-ms="1021" started-at="2018-08-02T15:55:48Z" finished-at="2018-08-02T15:55:49Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [24.53] but found [1.27]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [24.53] but found [1.27]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at com.c2info.EG360_DashboardTCs.TodayValues.verifyTodayPurchaseValue(TodayValues.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTodayPurchaseValue -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.c2info.EG360_DashboardTCs.TodayValues@42f93a98]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2018-08-02T15:55:48Z" finished-at="2018-08-02T15:55:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.c2info.EG360_DashboardTCs.TodayValues.verifyTodayPurchaseValue() throws java.sql.SQLException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.c2info.EG360_DashboardTCs.TodayValues@42f93a98]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-08-02T15:55:49Z" finished-at="2018-08-02T15:55:49Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyTodayPurchaseValue status=FAILURE method=TodayValues.verifyTodayPurchaseValue()[pri:1, instance:com.c2info.EG360_DashboardTCs.TodayValues@42f93a98] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="verifyTodayGRNValue()[pri:2, instance:com.c2info.EG360_DashboardTCs.TodayValues@42f93a98]" name="verifyTodayGRNValue" duration-ms="516" started-at="2018-08-02T15:55:49Z" finished-at="2018-08-02T15:55:49Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [109.98] but found [72.79]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [109.98] but found [72.79]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at com.c2info.EG360_DashboardTCs.TodayValues.verifyTodayGRNValue(TodayValues.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTodayGRNValue -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.c2info.EG360_DashboardTCs.TodayValues@42f93a98]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2018-08-02T15:55:49Z" finished-at="2018-08-02T15:55:49Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.c2info.EG360_DashboardTCs.TodayValues.verifyTodayGRNValue() throws java.sql.SQLException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.c2info.EG360_DashboardTCs.TodayValues@42f93a98]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-08-02T15:55:49Z" finished-at="2018-08-02T15:55:49Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyTodayGRNValue status=FAILURE method=TodayValues.verifyTodayGRNValue()[pri:2, instance:com.c2info.EG360_DashboardTCs.TodayValues@42f93a98] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.c2info.EG360_DashboardTCs.TodayValues@42f93a98]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2018-08-02T15:55:49Z" finished-at="2018-08-02T15:55:49Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.c2info.EG360_DashboardTCs.TodayValues.verifyTodayGDNValue() throws java.sql.SQLException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="verifyTodayGDNValue()[pri:3, instance:com.c2info.EG360_DashboardTCs.TodayValues@42f93a98]" name="verifyTodayGDNValue" duration-ms="514" started-at="2018-08-02T15:55:49Z" finished-at="2018-08-02T15:55:50Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [111.68] but found [0.71]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [111.68] but found [0.71]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at com.c2info.EG360_DashboardTCs.TodayValues.verifyTodayGDNValue(TodayValues.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTodayGDNValue -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.c2info.EG360_DashboardTCs.TodayValues@42f93a98]" name="afterMethod" is-config="true" duration-ms="1" started-at="2018-08-02T15:55:50Z" finished-at="2018-08-02T15:55:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyTodayGDNValue status=FAILURE method=TodayValues.verifyTodayGDNValue()[pri:3, instance:com.c2info.EG360_DashboardTCs.TodayValues@42f93a98] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="endTest()[pri:0, instance:com.c2info.EG360_DashboardTCs.TodayValues@42f93a98]" name="endTest" is-config="true" duration-ms="379" started-at="2018-08-02T15:55:50Z" finished-at="2018-08-02T15:55:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
      </class> <!-- com.c2info.EG360_DashboardTCs.TodayValues -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
