<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="ChethanBidare-pc" name="com.c2info.EG360_SalesReportsTCs.TC_011_VerifySalesReportForCurrentMonth_SalesReturn" tests="13" failures="2" timestamp="06 Aug 2018 05:19:36 GMT" time="100.355" errors="1">
  <testcase name="verifyBranchName" time="29.398" classname="com.c2info.EG360_SalesReportsTCs.TC_011_VerifySalesReportForCurrentMonth_SalesReturn"/>
  <testcase name="verifyBranchShortName" time="6.630" classname="com.c2info.EG360_SalesReportsTCs.TC_011_VerifySalesReportForCurrentMonth_SalesReturn"/>
  <testcase name="verifyBranchWiseNumberOfInvoices" time="6.742" classname="com.c2info.EG360_SalesReportsTCs.TC_011_VerifySalesReportForCurrentMonth_SalesReturn"/>
  <testcase name="verifyBranchwiseNumberOfCustomers" time="6.709" classname="com.c2info.EG360_SalesReportsTCs.TC_011_VerifySalesReportForCurrentMonth_SalesReturn"/>
  <testcase name="verifyBranchwiseDiscAmount" time="6.944" classname="com.c2info.EG360_SalesReportsTCs.TC_011_VerifySalesReportForCurrentMonth_SalesReturn"/>
  <testcase name="verifyBranchwiseInvoiceValAfterDisc" time="3.356" classname="com.c2info.EG360_SalesReportsTCs.TC_011_VerifySalesReportForCurrentMonth_SalesReturn">
    <failure type="java.lang.AssertionError" message="expected [233147.02] but found [233147.01]">
      <![CDATA[java.lang.AssertionError: expected [233147.02] but found [233147.01]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at com.c2info.EG360_SalesReportsTCs.TC_011_VerifySalesReportForCurrentMonth_SalesReturn.verifyBranchwiseInvoiceValAfterDisc(TC_011_VerifySalesReportForCurrentMonth_SalesReturn.java:168)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyBranchwiseInvoiceValAfterDisc -->
  <testcase name="verifyBranchwiseInvoiceValTax" time="6.477" classname="com.c2info.EG360_SalesReportsTCs.TC_011_VerifySalesReportForCurrentMonth_SalesReturn"/>
  <testcase name="verifyBranchwiseTaxAmount" time="2.928" classname="com.c2info.EG360_SalesReportsTCs.TC_011_VerifySalesReportForCurrentMonth_SalesReturn">
    <failure type="java.lang.AssertionError" message="expected [27587.76] but found [27549.14]">
      <![CDATA[java.lang.AssertionError: expected [27587.76] but found [27549.14]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at com.c2info.EG360_SalesReportsTCs.TC_011_VerifySalesReportForCurrentMonth_SalesReturn.verifyBranchwiseTaxAmount(TC_011_VerifySalesReportForCurrentMonth_SalesReturn.java:218)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyBranchwiseTaxAmount -->
  <testcase name="verifyBranchwiseCGSTAmount" time="6.730" classname="com.c2info.EG360_SalesReportsTCs.TC_011_VerifySalesReportForCurrentMonth_SalesReturn"/>
  <testcase name="verifyBranchwiseSGSTAmount" time="7.249" classname="com.c2info.EG360_SalesReportsTCs.TC_011_VerifySalesReportForCurrentMonth_SalesReturn"/>
  <testcase name="verifyBranchwiseIGSTAmount" time="3.232" classname="com.c2info.EG360_SalesReportsTCs.TC_011_VerifySalesReportForCurrentMonth_SalesReturn">
    <error type="java.sql.SQLSyntaxErrorException" message="You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near &#039;d_date&gt;=&#039;2018-08-01&#039; and d_date&lt;=&#039;2018-08-31&#039; and n_cancel_flag=0&#039; at line 1">
      <![CDATA[java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'd_date>='2018-08-01' and d_date<='2018-08-31' and n_cancel_flag=0' at line 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:118)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:95)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1247)
	at com.c2info.EG360_Database.Database.getData(Database.java:34)
	at com.c2info.EG360_SalesReportsTCs.TC_011_VerifySalesReportForCurrentMonth_SalesReturn.verifyBranchwiseIGSTAmount(TC_011_VerifySalesReportForCurrentMonth_SalesReturn.java:286)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verifyBranchwiseIGSTAmount -->
  <testcase name="verifyBranchwiseCessAmount" time="7.180" classname="com.c2info.EG360_SalesReportsTCs.TC_011_VerifySalesReportForCurrentMonth_SalesReturn"/>
  <testcase name="verifyBranchwiseServiceChargeAmount" time="6.780" classname="com.c2info.EG360_SalesReportsTCs.TC_011_VerifySalesReportForCurrentMonth_SalesReturn"/>
</testsuite> <!-- com.c2info.EG360_SalesReportsTCs.TC_011_VerifySalesReportForCurrentMonth_SalesReturn -->
